instr_sources = {}
instr_sources[0]='function(){var C=x.pop();x.push(C[0][C[1]])}'
instr_sources[1]='function(){x[x[x.length-2][0]][0]=x[x.length-1]}'
instr_sources[2]='function(){x[x.length-2]=x[x.length-2]<<x.pop()}'
instr_sources[3]='function(){x.push(typeof x.pop())}'
instr_sources[4]='function(){x.push(null)}'
instr_sources[5]='function(){x[x.length-2]=x[x.length-2]==x.pop()}'
instr_sources[6]='function(){var C=x.pop(),I=x[x.length-1];x[I[0]][0]=C[0][C[1]]}'
instr_sources[7]='function(){x.push([x.pop(),x.pop()].reverse())}'
instr_sources[8]='function(){x[x.length-1]=G[f++]}'
instr_sources[9]='function(){I.push([G[f++],x.length,G[f++]])}'
instr_sources[10]='function(){x.length-=G[f++]}'
instr_sources[11]='function(){x[x.length-2]=x[x.length-2]in x.pop()}'
instr_sources[12]='function(){var C=x.pop();x.push([x[x.pop()][0],C])}'
instr_sources[13]="nop"
instr_sources[14]='function(){var C=G[f++],I=x[x.length-2-C];x[x.length-2-C]=x.pop(),x.push(I)}'
instr_sources[15]='function(){x.push(x[x.length-1])}'
instr_sources[16]='function(){x.push([x.pop()])}'
instr_sources[17]="nop"
instr_sources[18]='function(){var C=G[f++],I=C?x.slice(-C):[];x.length-=C,I.unshift(null),x.push(new(Function.prototype.bind.apply(x.pop(),I)))}'
instr_sources[19]="nop"
instr_sources[20]="nop"
instr_sources[21]='function(){x.push(~x.pop())}'
instr_sources[22]='function(){x[x.length-2]=x[x.length-2]&x.pop()}'
instr_sources[23]='function(){f=G[f++]}'
instr_sources[24]='function(){x.pop()}'
instr_sources[25]='function(){var C=G[f++],I=C?x.slice(-C):[];x.length-=C,x.push(x.pop().apply(w,I))}'
instr_sources[26]='function(){x.push([w,x.pop()])}'
instr_sources[27]='function(){x[x.length-2]=x[x.length-2]+x.pop()}'
instr_sources[28]='function(){var C=x.pop();x.push(delete C[0][C[1]])}'
instr_sources[29]='function(){x[x.length-2]=x[x.length-2]-x.pop()}'
instr_sources[30]='function(){var C=x[x.length-2];C[0][C[1]]=x[x.length-1]}'
instr_sources[31]='function(){x.push(G[f++])}'
instr_sources[32]='function(){x[x.length-2]=x[x.length-2]^x.pop()}'
instr_sources[33]='function(){x[x.length-2]=x[x.length-2]|x.pop()}'
instr_sources[34]='function(){x[x.length-2]=x[x.length-2]/x.pop()}'
instr_sources[35]='function(){x[x.length-2]=x[x.length-2]>=x.pop()}'
instr_sources[36]='function(){var C=G[f++],I=C?x.slice(-C):[];x.length-=C,I.unshift(null);var g=x.pop();x.push(new(Function.prototype.bind.apply(g[0][g[1]],I)))}'
instr_sources[37]='function(){x.push(!x.pop())}'
instr_sources[38]="nop"
instr_sources[39]='function(){x[x.length-2]=x[x.length-2]>>>x.pop()}'
instr_sources[40]='function(){x.push(undefined)}'
instr_sources[41]='function(){x.push(!0)}'
instr_sources[42]='function(){x.push(!1)}'
instr_sources[43]='function(){x[x.length-2]=x[x.length-2]>>x.pop()}'
instr_sources[44]='function(){for(var g=G[f++],Q=[],C=G[f++],I=G[f++],H=[],A=0;A<C;A++)Q[G[f++]]=x[G[f++]];for(A=0;A<I;A++)H[A]=G[f++];x.push(function B(){var C=Q.slice(0);C[0]=[this],C[1]=[arguments],C[2]=[B];for(var I=0;I<H.length&&I<arguments.length;I++)0<H[I]&&(C[H[I]]=[arguments[I]]);return __TENCENT_CHAOS_VM(g,G,w,C,h,b,t)})}'
instr_sources[45]='function(){x.push("")}'
instr_sources[46]='function(){x[x.length-2]=x[x.length-2]*x.pop()}'
instr_sources[47]='function(){g=null}'
instr_sources[48]="nop"
instr_sources[49]='function(){I.pop()}'
instr_sources[50]='function(){x.push(x[x.pop()[0]][0])}'
instr_sources[51]='function(){var C=x.pop(),I=x[x.length-1];I[0][I[1]]=x[C[0]][0]}'
instr_sources[52]='function(){var C=G[f++];x[x.length-1]&&(f=C)}'
instr_sources[53]='function(){throw x[x.length-1]}'
instr_sources[54]='function(){return!0}'
instr_sources[55]='function(){x[x.length-2]=x[x.length-2]%x.pop()}'
instr_sources[56]='function(){x.length=G[f++]}'
instr_sources[57]="nop"
instr_sources[58]='function(){x[x.length-2]=x[x.length-2]===x.pop()}'
instr_sources[59]="nop"
instr_sources[60]='function(){var C=x.pop(),I=x[x.length-1];I[0][I[1]]=C[0][C[1]]}'
instr_sources[61]='function(){x[x.length-2]=x[x.length-2]>x.pop()}'
instr_sources[62]='function(){x[x[x.length-1][0]]=x[x[x.length-1][0]]===undefined?[]:x[x[x.length-1][0]]}'
instr_sources[63]='function(){var C=x.pop(),I=x.pop();x.push([I[0][I[1]],C])}'
instr_sources[64]='function(){var C=G[f++],I=C?x.slice(-C):[];x.length-=C;var g=x.pop();x.push(g[0][g[1]].apply(g[0],I))}'
instr_sources[65]="nop"
instr_sources[66]='function(){x[x.length-2]+=String.fromCharCode(G[f++]+x[x.length-1])}'
instr_sources[67]='function(){return!!g}'
pos_var='f'
stack_var='x'
program_var='G'